### ISSUE TITLE
Clarification Quesiton on Driver install

### ISSUE THREAD

**Issue by alexanderjacuna** [Bytelake/Coral-in-LXC#5]
Does the driver for the Coral TPU installed to the LXC or the Proxmox host itself? I have see information around that suggests blacklisting the driver for the Coral TPU on the Proxmox host so just confirming where you installed the driver for your solution.

**Comment by Bytelake** [comment]
The driver is installed on the host

**Comment by alexanderjacuna** [comment]
Thanks appreciate it dude.
